name: Marco Sero
description: Reading. Coding. Writing.
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: /blog/page:num
permalink: /blog/:title/
url: https://marcosero.com
plugins: [jekyll-paginate, jekyll-redirect-from]
gems:
  - jemoji
