name: Marco Sero
description: Reading. Coding. Writing.
markdown: kramdown
highlighter: pygments
paginate: 5
paginate_path: /blog/page:num
permalink: /blog/:title
url: http://www.marcosero.com
plugins: [jekyll-paginate]
gems:
  - jemoji
